services:
  - type: web
    name: ai-health-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.10.13   
    envVars:
      - key: PORT
        value: 5001
