services:
  - type: web
    name: ai-health-backend
    env: python
    plan: free
    build:
      buildCommand: pip install -r requirements.txt
      env:
        PYTHON_VERSION: 3.10.13
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 5001
